channel_sources:                              # [win]
  - conda-forge/label/meson_dev,conda-forge   # [win]
mpi:
  - nompi
  - mpich    # [not win]
  - openmpi  # [not win]
#fortran_compiler:              # [win]
#  - flang                      # [win]
#fortran_compiler_version:      # [win]
#  - 17                         # [win]