{% set release = "v3.1.0" %}
{% set version = "3.1.0" %}
{% set name = "wisdem" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    url: https://github.com/WISDEM/WISDEM/archive/{{ release }}.tar.gz
    # Download the tar-ball and do: openssl sha256 file.tar.gz to update
    sha256: 203ae9c886bb78999c1fd80bab728d2e07f74522dc4188aba34429527cdc7e26
    
build:
    number: 1
    script: "{{ PYTHON }} -m pip install . --no-deps -vv"
    skip: true    # [py<37]

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        - {{ compiler('m2w64_c') }}    # [win]
        - {{ compiler('m2w64_cxx') }}    # [win]
        - make
    host:
        - libblas
        - libcblas
        - liblapack
        - libpython    # [win]
        - python
        - pip
        - numpy
        - setuptools
        - cython
    run:
        - python
        # Putting regular numpy is 'host' section and pin_compatible here per conda-forge guidance
        - {{ pin_compatible('numpy') }}
        - scipy
        - pandas
        - openpyxl
        - xlrd
        - cython
        - swig
        - jsonschema
        - ruamel_yaml
        - pyyaml
        - openmdao
        - pytest
        - pyside2
        - matplotlib-base
#        - mpi4py    # [not win] # Fails on conda-forge linux, ask users to do separately
#        - petsc4py    # [not win] # Fails on conda-forge linux, ask users to do separately

test:
    # Fails unless we create conda package for simpy, marmot-agents
    imports:
        - wisdem

about:
    home: https://www.nrel.gov/wind/systems-engineering-models-tools.html
    license: Apache-2.0
    license_file: LICENSE
    summary: Wind-Plant Integrated System Design and Engineering Model
    description: |
        The Wind-Plant Integrated System Design and Engineering Model (WISDEM®) is a
        set of models for assessing overall wind plant cost of energy (COE). The models
        use wind turbine and plant cost and energy production as well as financial
        models to estimate coe and other wind plant system attributes. It is built
        in OpenMDAO.
    doc_url: https://wisdem.readthedocs.io
    dev_url: https://github.com/wisdem/wisdem

extra:
    recipe-maintainers:
        - ptrbortolotti
        - gbarter
        - johnjasa
        
