{% set release = "v3.8.5" %}
{% set version = "3.8.5" %}
{% set name = "wisdem" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/WISDEM/WISDEM/archive/{{ release }}.tar.gz
    # Download the tar-ball and do: openssl sha256 file.tar.gz to update
  sha256: 2a92c7139afb765a38ad262575aca1136ac18a3bebf5f3a5832407807e2f588e

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  #script: {{ PYTHON }} setup.py install

requirements:
  build:
    - {{ compiler('c') }}         # [not win]
    - {{ compiler('fortran') }}
    - {{ compiler('m2w64_c') }}   # [win]
    - make
    - meson
    - ninja
    - numpy
    - pkg-config
    - python
  host:
    - libblas
    - liblapack
    - libpython        # [win]
    - python
    - pip
    - numpy
    - setuptools
    - cython
  run:
    - cython
    - jsonschema
    - matplotlib-base
    - nlopt
    - {{ pin_compatible('numpy') }}
    - openmdao >=3.18
    - openpyxl
    - pandas
    - pydoe2
    - pyoptsparse
    - pytest
    - python
    - python-benedict
    - pyyaml
    - ruamel_yaml
    - scipy
    - simpy
    - sortedcontainers
    - statsmodels
    - swig

# DO NOT ADD MPI- it breaks the conda build.  Users have to add it afterwards
# Putting numpy in 'host' section and pin_compatible in run per conda-forge guidance
    
test:
  imports:
    - wisdem
  requires:
      - pip
      - pytest
  commands:
      - pip check
      - pytest wisdem/test/test_gluecode

about:
  home: https://wisdem.readthedocs.io
  license: Apache-2.0
  license_file: LICENSE
  summary: Wind-Plant Integrated System Design and Engineering Model
  description: |
    The Wind-Plant Integrated System Design and Engineering Model (WISDEM®) is a
    set of models for assessing overall wind plant cost of energy (COE). The models
    use wind turbine and plant cost and energy production as well as financial
    models to estimate coe and other wind plant system attributes. WISDEM is developed by
    the National Renewable Energy Lab, on top of NASA's OpenMDAO library.
  doc_url: https://wisdem.readthedocs.io
  dev_url: https://github.com/wisdem/wisdem

extra:
  recipe-maintainers:
    - ptrbortolotti
    - gbarter
